- signatures/latest.json
This reverts commit 7af056c9a21e0a0dfaba18686b2f1ecc291f4a2e.
> Revert "Signature update. Add sles11sp4."

- manuals/2.8.0/5/3_-_Web_Authorization.html
- manuals/2.8.0/5/4_-_Locking_Down_Cobbler.html
I provided a fix for the issue described [here](https://github.com/cobbler/cobbler/issues/1958).
> Fix broken links on Locking Down Cobbler (V2.8.0).

- signatures/2.8.x/latest.json
> Add JSON Signatures from the 2.8.x branch

- signatures/3.0.x/latest.json
This is a port of the change applied on the main cobbler project (commit 1f5383e7aa6f60d0e3b7825aed20951cc2a5acf1 - in branch master).
> Correct opensuse15.0 and Add opensuse15.1 (v3.0)

- signatures/2.8.x/latest.json
This is a port of the change applied on the main cobbler project (commit 1ca3d324989c768fc0212d779796056a1ef79b12 - in branch relaese28).
> Correct opensuse15.0 and Add opensuse15.1 (v2.8)

- signatures/2.6.x/latest.json
This takes the signatures from cobbler master and updates the website so every user can get them via the `signature update` command.
> Update 26 signatures

- signatures/latest.json
This takes the signatures from cobbler master and updates the website so every user can get them via the `signature update` command.
> Update Latest signatures

- signatures/2.8.x/latest.json
This takes the signatures from cobbler master and updates the website so every user can get them via the `signature update` command.
> Updates 28 signatures

- _config.yml
- _includes/navigation.html
- _posts/2019-10-20-cobbler_3.0.1_released.md
- downloads/3.0.x.md
- index.md
> Create information for 3.0.x

- blog/index.html
This should fix pagination on blog page. Haven't tested it, just put in findings by @xenlo.
> fix pagination

- signatures/2.8.x/latest.json
- signatures/3.0.x/latest.json
- signatures/latest.json
Added Ubuntu focal as per request in https://github.com/cobbler/cobbler/issues/2395
This is not tested and not a solution for our cloud-init problem.
> Signatures: Add Ubuntu Focal

- signatures/3.0.x/latest.json
Apply last changes from cobbler/cobbler.
> Apply last updates from signatures

- signatures/2.8.x/latest.json
- signatures/3.0.x/latest.json
- signatures/latest.json
Signed-off-by: leereyno <leebreynolds@gmail.com>
Add support for Rocky linux to cobbler signatures refreshed by "cobbler signature update"
> Add Rocky Linux support

- signatures/3.0.x/latest.json
- signatures/latest.json
As requested in cobbler/cobbler#2713
> Added fedora34 to 3.0x signatures

- _posts/2021-09-21-cobbler_3.2.2_released.md
- _posts/2021-09-21-cobbler_3.3.0_released.md
> Add Cobbler 3.3.0 and 3.2.2 release notes

- _config.yml
- _includes/footer.html
- downloads/3.x.x.md
This PR fixes some small issues with the 3.3.0 release and adjusts the developer link in the footer.
> Fixups for the 3.3.0 release

- signatures/latest.json
Sync distro signatures with signatures from cobbler codebase.
> Sync distro signatures

- .github/workflows/build.yml
- _posts/2024/2024-07-04-community-repositories.md
Fixes https://github.com/cobbler/cobbler/issues/2667
> Blog: Add entry for community repos

- .github/workflows/build.yml
- _config.yml
- _posts/2024/2024-07-05-cobbler_3.3.5_released.md
- downloads/3.x.x.md
See title. Includes a fix for the CI that shows if the site builds.
> Release 3.3.5

- _config.yml
- _posts/2024/2024-07-16-cobbler_3.3.6_released.md
> Add 3.3.6 version announcement
